### ISSUE TITLE
Autologin links should be generated on the server

### ISSUE THREAD

**Issue by MrApplejuice** [MrApplejuice/wp-autologin-links#2]
Currently, newly generated login are created in JavaScript. This is quite a but unsafer than to create the links on the server where the random generator can be controlled.

Verdict: Change must happen!

**Comment by beeing** [comment]
Hi, nice plugin. Just an idea for this, you can expose this as REST API that allow creation of link programmatically.

Also, if you can include perishable link, meaning only used once then this can be quite perfect for integration with external systems.

**Comment by MrApplejuice** [comment]
Hey beeing! Yes. The REST API is a good idea. I am working on a bigger revamp in my off-time. This is a step towards that. The bigger update will support a bit more automation with the plugin than there is possible at the moment. I think this is not part of this issue, but feel free to open a new issue for this suggestion. Sounds like a good idea.

**Comment by MrApplejuice** [comment]
Just committed the first draft version for server-side code generation and verified it works by testing against multiple wordpress version. 

**TODO**

- [ ] Check if the nonce handling is valid and secure

**Comment by MrApplejuice** [comment]
- [ ] Add UI interactions
- [ ] Add delete-link functions

**Comment by MrApplejuice** [comment]
- [ ] Nonces do not time out and are not specific to the previous login code. They should be. As a result, the nonce action name for generated ajax-nonces should be a mix of
  - Timestamp (`wp nonce tick`)
  - old login code
  - specific action name
- [ ] Check if the nonce can be omitted from the AJAX request for security reasons
